# Generated by Django 4.1 on 2022-10-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
