# Generated by Django 4.1 on 2022-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_account_is_active_currency_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='from_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
    ]
